services:
  dumpster-maintenance:
    image: caddy:alpine
    ports:
      - "8000"
    volumes:
      - maintenance-html:/srv
    command: caddy run --config /srv/Caddyfile --adapter caddyfile

volumes:
  maintenance-html:
