version: "1.1"
name: dumpster
description: "Dumpster Launchpad - full stack (frontend + backend + database + cache)"
repos:
  - github.com/gorbagana-dev/dumpster-frontend
  - github.com/gorbagana-dev/dumpster-backend
  - github.com/gorbagana-dev/dumpster-docs
containers:
  - cerc/dumpster-backend
  - cerc/dumpster-frontend
  - cerc/dumpster-docs
pods:
  - dumpster
